# Generated by Django 5.1.2 on 2024-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=20)),
                ('ambientes', models.IntegerField()),
                ('precio', models.CharField(max_length=20)),
            ],
        ),
    ]
