# Generated by Django 5.1.2 on 2024-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='casa',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
